//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelDesktopApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelRoom
    {
        public int roomID { get; set; }
        public Nullable<int> roomNumb { get; set; }
        public Nullable<int> floorOfHotel { get; set; }
        public Nullable<int> numbOfBed { get; set; }
        public Nullable<int> roomSize { get; set; }
        public Nullable<int> cleaningStatus { get; set; }
        public bool isUsed { get; set; }
        public Nullable<int> resNumb { get; set; }
    }
}
