//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelDesktopApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReservationTable
    {
        public int ResID { get; set; }
        public Nullable<int> ResNumb { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string DateStart { get; set; }
        public string DateEnd { get; set; }
        public Nullable<int> RoomSize { get; set; }
        public Nullable<int> BedNumb { get; set; }
        public Nullable<int> RoomID { get; set; }
    }
}
