//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBAccess
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Customer
    {
        public int ID { get; set; }

        [Required(ErrorMessage = "Please Enter Username..")]
        [DisplayName("First name")]
        public string FirstName { get; set; }

        [DisplayName("Last Name")]
        public string LastName { get; set; }

        [DisplayName("Password")]
        [DataType(DataType.Password)]
        public string Pass { get; set; }
        public Nullable<int> ResID { get; set; }

        public string LoginErrorMessage { get; set; }
    }
}
